global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]